baseURL: https://scalio.blog/
languageCode: en-us
title: Roman Godmaire
theme: PaperMod

copyright: "Licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
rssLimit: 50

frontmatter:
  - lastmod:
      - lastmod
      - date
      - publishDate

outputs:
  home:
    - HTML
    - RSS
    - JSON  # Used for search

menu:
  main:
    - name: "Search"
      url: "search"
    - name: "Tags"
      url: "tags"

taxonomies:
  tag: tags
  # series: series

params:
  defaultTheme: auto
  ShowReadingTime: true

  editPost:
    URL: "https://github.com/digyx/blog/tree/main/content"
    Text: "Suggest changes on Github"
    appendFilePath: true


  homeInfoParams:
      Title: Welcome to the Dregs of My Mind
      Content: |
        Honestly, I'm just making it up as I go along.

        Don't take anything I write seriously.

  socialIcons:
    - name: "Mastodon"
      url: "https://mstdn.social/@godmaire"
    - name: "Github"
      url: "https://github.com/digyx"
    - name: "RSS"
      url: "index.xml"
